routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('register', function () {
	abort(404);
});
Route::post('register', function () {
	abort(404);
});

Route::get('/', function () {
	return redirect()->route('templates.index');
});
Route::get('message.jpg', 'Controller@messageViewed')->name('message.view');

Route::middleware(['auth'])->group(function () {
	Route::resource('templates', 'TemplateController');
	Route::resource('users', 'UserController');
	Route::resource('import', 'ImportController')->only(['index', 'store']);
	Route::get('messages', 'MessageController@index')->name('messages.index');	
	Route::post('mailing', 'Controller@mailingRun')->name('mailing.run');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use \PhpOffice\PhpSpreadsheet\IOFactory;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'password', 
        'name',
        'position',
        'email',
        'company_name',
        'firstname',
        'lastname',
        'patronymic',
        'fullname',
        'postcode',
        'description',
        'city',
        'phone_work',
        'phone_personal',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    // список пользователей без теущего авторизировнного
    public static function getList($qty = 50) {
        return self::where('id', '<>', auth()->user()->id)
            ->orderBy('id', 'desc')
            ->paginate($qty);
    }

    protected static $directives = [
            'name',
            'position',
            'email',
            'company_name',
            'firstname',
            'lastname',
            'patronymic',
            'fullname',
            'postcode',
            'description',
            'city',
            'phone_work',
            'phone_personal',
        ];

    public static function getDirectives() {
        return self::$directives;
    }

    public function getMessages() {
        return $this->belongsToMany('App\models\Template');
    }

    public static function importFromCsv($request) {
        $f = fopen($request->file->path(), 'r');

        // соотнести ключи
        $headers = fgetcsv($f, 0, $request->delimeter);
        $keys = [];
        foreach ($headers as $key => $head) {
            $keys[$head] = $key;
        }

        $finish_keys = [];
        foreach ($request->relations as $i => $relation) {
            $finish_keys[$relation['to']] = $keys[$relation['from']];
        }

        while ($row = fgetcsv($f, 0, $request->delimeter)) {
            $data = [];
            foreach ($finish_keys as $key => $value) {
                $data[$key] = $row[$value];
            }
            // dd($data);
            $user = User::where('email', $data['email'])->first();
            if ($user) {
                if ($request->replace) {
                    $user->update($data);
                }
            }else{
                User::create($data);
            }
        }
        fclose($f);
    }

    public static function importFromExcel($request) {
        $filename = $request->file->path();
        $spreadsheet = IOFactory::load($filename);
        $activesheet = $spreadsheet->getActiveSheet();

        $headers = [];
        for ($i = 'A'; $i <= 'Z'; $i++) {
            $value = $activesheet->getCell($i.'1')->getValue();
            if ($value === null || !strlen(trim($value))) continue;
            $headers[$i] = $value;
        }

        $keys = [];
        foreach ($headers as $key => $head) {
            $keys[$head] = $key;
        }
        $finish_keys = [];
        foreach ($request->relations as $i => $relation) {
            $finish_keys[$keys[$relation['from']]] = $relation['to'];
        }
        $maxNumRows = $activesheet->getHighestDataRow();
        $maxNumColumns = $activesheet->getHighestDataColumn();
        for ($i = 1; $i <= $maxNumRows; $i++) {
            $data = [];

            for ($j = 'A'; $j <= $maxNumColumns; $j++) {
                if (isset($finish_keys[$j])) {
                    $data[$finish_keys[$j]] = $activesheet->getCell($j.$i)->getValue();
                }
            }

            // если не задан email - не создавать запись в users
            if (!isset($data['email'])) {
                continue;
            }

            if (!self::isValidEmail($data['email'])) {
                // если там что-то есть - пытаемся разбить на email-ы
                if (strlen(trim($data['email'])) > 0) {
                    $emails = explode(',', $data['email']);
                    foreach ($emails as $email) {
                        $email = trim($email);
                        if (self::isValidEmail($email)) {
                            self::createOrUpdate(array_merge($data, compact('email')));
                        }
                    }
                }
                continue;
            } else self::createOrUpdate($data);
        }
    }

    public static function createOrUpdate($data) {
        $user = User::where('email', $data['email'])->first();
        // если пользователь найден и флаг - перезаписать данные
        if ($user && request()->replace) {
            $user->update($data);
        }
        // если пользователь не найден - создать
        if (!$user) {
            $user = User::create($data);
        }
        return $user;
    }

    public static function isValidEmail($email) {
        return filter_var($email, FILTER_VALIDATE_EMAIL);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\models\Template;
use App\Http\Requests\User\Store;
use App\Http\Requests\User\Update;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $currentQty = $request->qty ?? 50;
        $qty = [50, 100, 200, 300, 400, 500];
        $users = User::getList($currentQty);
        $templates = Template::all();

        $data = compact('users', 'templates', 'qty', 'currentQty');
        return view('users.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Store $request)
    {
        $user = User::create($request->all() + ['password' => '123']);
        if (!$user) {
            return back()->with('error', 'Ошибка. Пользователь не создан.');
        }
        return redirect()->route('users.edit', $user)->with('success', 'Пользователь успешно создан.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return redirect()->route('users.edit', $user);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $data = compact('user');
        return view('users.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Update $request, User $user)
    {
        $user->update($request->all());
        return back()->with('success', 'Данные пользователя обновлены.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->route('users.index')->with('success', 'Пользователь удален.');
    }
}

resources/views/users/create.blade.php
@extends('layouts.mailing')

@section('title')
    Создание нового пользователя
@endsection

@section('content')
    {{ Form::open(['url' => route('users.store')]) }}
    <div>
        <div class="form-group">
            {{ Form::label('email', 'Email *', ['class' => 'label-control']) }}
            {{ Form::text('email', null, ['class' => 'form-control', 'id' => 'email', 'placeholder' => 'Введите Email']) }}
        </div>
        <div class="form-group">
            {{ Form::label('name', 'Название', ['class' => 'label-control']) }}
            {{ Form::text('name', null, ['class' => 'form-control', 'id' => 'name', 'placeholder' => 'Введите название']) }}
        </div>


        <div class="form-group">
            {{ Form::label('position', 'Должность', ['class' => 'label-control']) }}
            {{ Form::text('position', null, ['class' => 'form-control', 'id' => 'position', 'placeholder' => 'Введите должность']) }}
        </div>

        <div class="form-group">
            {{ Form::label('company_name', 'Название компании', ['class' => 'label-control']) }}
            {{ Form::text('company_name', null, ['class' => 'form-control', 'id' => 'company_name', 'placeholder' => 'Введите название компании']) }}
        </div>

        <div class="form-group">
            {{ Form::label('firstname', 'Имя', ['class' => 'label-control']) }}
            {{ Form::text('firstname', null, ['class' => 'form-control', 'id' => 'firstname', 'placeholder' => 'Введите имя']) }}
        </div>

        <div class="form-group">
            {{ Form::label('lastname', 'Фамилия', ['class' => 'label-control']) }}
            {{ Form::text('lastname', null, ['class' => 'form-control', 'id' => 'lastname', 'placeholder' => 'Введите фамилию']) }}
        </div>

        <div class="form-group">
            {{ Form::label('patronymic', 'Отчество', ['class' => 'label-control']) }}
            {{ Form::text('patronymic', null, ['class' => 'form-control', 'id' => 'patronymic', 'placeholder' => 'Введите отчество']) }}
        </div>

        <div class="form-group">
            {{ Form::label('fullname', 'ФИО', ['class' => 'label-control']) }}
            {{ Form::text('fullname', null, ['class' => 'form-control', 'id' => 'fullname', 'placeholder' => 'Введите ФИО']) }}
        </div>

        <div class="form-group">
            {{ Form::label('postcode', 'Почтовый индекс', ['class' => 'label-control']) }}
            {{ Form::text('postcode', null, ['class' => 'form-control', 'id' => 'postcode', 'placeholder' => 'Введите почтовый индекс']) }}
        </div>

        <div class="form-group">
            {{ Form::label('description', 'Описание', ['class' => 'label-control']) }}
            {{ Form::text('description', null, ['class' => 'form-control', 'id' => 'description', 'placeholder' => 'Введите описание']) }}
        </div>

        <div class="form-group">
            {{ Form::label('city', 'Город', ['class' => 'label-control']) }}
            {{ Form::text('city', null, ['class' => 'form-control', 'id' => 'city', 'placeholder' => 'Введите город']) }}
        </div>
        <div class="form-group">
            {{ Form::label('phone_work', 'Рабочий телефон', ['class' => 'label-control']) }}
            {{ Form::text('phone_work', null, ['class' => 'form-control', 'id' => 'phone_work', 'placeholder' => 'Введите рабочий телефон']) }}
        </div>
        <div class="form-group">
            {{ Form::label('phone_personal', 'Личный телефон', ['class' => 'label-control']) }}
            {{ Form::text('phone_personal', null, ['class' => 'form-control', 'id' => 'phone_personal', 'placeholder' => 'Введите личный телефон']) }}
        </div>
    </div>
    <div class="form-group text-center">
            {{ Form::submit('Создать', ['class' => 'btn btn-primary']) }}
            {{ Html::tag('a', 'Назад', ['href' => route('users.index'), 'class' => 'btn btn-outline-secondary']) }}        
    </div>
    {{ Form::close() }}
@endsection

resources/views/users/edit.blade.php
@extends('layouts.mailing')

@section('title')
    Редактирование пользователя
@endsection

@section('content')
    {{ Form::model($data['user'], ['url' => route('users.update', $data['user']), 'method' => 'patch']) }}

    <div>
        <div class="form-group">
            {{ Form::label('email', 'Email *', ['class' => 'label-control']) }}
            {{ Form::text('email', null, ['class' => 'form-control', 'id' => 'email', 'placeholder' => 'Введите Email']) }}
        </div>
        <div class="form-group">
            {{ Form::label('name', 'Название', ['class' => 'label-control']) }}
            {{ Form::text('name', null, ['class' => 'form-control', 'id' => 'name', 'placeholder' => 'Введите название']) }}
        </div>


        <div class="form-group">
            {{ Form::label('position', 'Должность', ['class' => 'label-control']) }}
            {{ Form::text('position', null, ['class' => 'form-control', 'id' => 'position', 'placeholder' => 'Введите должность']) }}
        </div>

        <div class="form-group">
            {{ Form::label('company_name', 'Название компании', ['class' => 'label-control']) }}
            {{ Form::text('company_name', null, ['class' => 'form-control', 'id' => 'company_name', 'placeholder' => 'Введите название компании']) }}
        </div>

        <div class="form-group">
            {{ Form::label('firstname', 'Имя', ['class' => 'label-control']) }}
            {{ Form::text('firstname', null, ['class' => 'form-control', 'id' => 'firstname', 'placeholder' => 'Введите имя']) }}
        </div>

        <div class="form-group">
            {{ Form::label('lastname', 'Фамилия', ['class' => 'label-control']) }}
            {{ Form::text('lastname', null, ['class' => 'form-control', 'id' => 'lastname', 'placeholder' => 'Введите фамилию']) }}
        </div>

        <div class="form-group">
            {{ Form::label('patronymic', 'Отчество', ['class' => 'label-control']) }}
            {{ Form::text('patronymic', null, ['class' => 'form-control', 'id' => 'patronymic', 'placeholder' => 'Введите отчество']) }}
        </div>

        <div class="form-group">
            {{ Form::label('fullname', 'ФИО', ['class' => 'label-control']) }}
            {{ Form::text('fullname', null, ['class' => 'form-control', 'id' => 'fullname', 'placeholder' => 'Введите ФИО']) }}
        </div>

        <div class="form-group">
            {{ Form::label('postcode', 'Почтовый индекс', ['class' => 'label-control']) }}
            {{ Form::text('postcode', null, ['class' => 'form-control', 'id' => 'postcode', 'placeholder' => 'Введите почтовый индекс']) }}
        </div>

        <div class="form-group">
            {{ Form::label('description', 'Описание', ['class' => 'label-control']) }}
            {{ Form::text('description', null, ['class' => 'form-control', 'id' => 'description', 'placeholder' => 'Введите описание']) }}
        </div>

        <div class="form-group">
            {{ Form::label('city', 'Город', ['class' => 'label-control']) }}
            {{ Form::text('city', null, ['class' => 'form-control', 'id' => 'city', 'placeholder' => 'Введите город']) }}
        </div>
        <div class="form-group">
            {{ Form::label('phone_work', 'Рабочий телефон', ['class' => 'label-control']) }}
            {{ Form::text('phone_work', null, ['class' => 'form-control', 'id' => 'phone_work', 'placeholder' => 'Введите рабочий телефон']) }}
        </div>
        <div class="form-group">
            {{ Form::label('phone_personal', 'Личный телефон', ['class' => 'label-control']) }}
            {{ Form::text('phone_personal', null, ['class' => 'form-control', 'id' => 'phone_personal', 'placeholder' => 'Введите личный телефон']) }}
        </div>
    </div>
    <div class="form-group text-center">
            {{ Form::submit('Сохранить', ['class' => 'btn btn-primary']) }}
            {{ Html::tag('a', 'Назад', ['href' => route('users.index'), 'class' => 'btn btn-outline-secondary']) }}        
    </div>
    {{ Form::close() }}
@endsection

resources/views/users/index.blade.php
@extends('layouts.mailing')

@section('title')
    Список всех пользователей
@endsection

@section('content')
    <div class="row">
        <div class="col-12 col-md-6">
            <div class="form-group">
                <a class="btn btn-primary" href="{{ route('users.create') }}">Создать <i class="fa fa-plus ml-1"></i></a>
                <a class="btn btn-primary" href="{{ route('import.index') }}">Импорт <i class="fas fa-upload ml-1"></i></a>
            </div>
        </div>
        <div class="col-12 col-md-6">
            {{ Form::open(['url' => route('mailing.run'), 'onsubmit' => 'return validateMailingForm($(this))']) }}    
                <input type="hidden" name="users">            
                <div class="input-group">
                    <select name="template_id" class="custom-select" onclick="removeIsInvalidClass($(this))">
                        <option selected disabled>Выберите шаблон письма...</option>
                        @foreach ($data['templates'] as $template)
                            <option value="{{ $template->id }}">{{ $template->name }}</option>
                        @endforeach
                    </select>
                    <div class="input-group-append">
                        <button class="btn btn-primary run-mailing" type="submit">Запустить</button>
                    </div>
                </div>   
            {{ Form::close() }}
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-2 mt-3 mb-3">
            <select class="number-view custom-select">
                @foreach ($data['qty'] as $one)
                    <option {{ $data['currentQty'] == $one ? 'selected' : '' }} value="{{ $one }}">{{ $one }}</option>
                @endforeach
            </select>
        </div>
    </div>

    {{ $data['users']->links() }}
    <table class="table table-striped">
        <thead>
            <th>
                <input class="custom-control users-checkbox" type="checkbox">
            </th>
            <th>#</th>
            <th>email</th>
            <th class="w-25">Название</th>
            <th class="w-25">Должность</th>
            <th class="w-25">&nbsp;</th>
        </thead>
        <tbody>
            @foreach ($data['users'] ?? [] as $user)
                <tr>
                    <td>
                        <input data-user-id="{{ $user->id }}" class="custom-control user-checkbox" type="checkbox">
                    </td>
                    <td>{{ $user->id }}</td>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->position }}</td>
                    <td class="text-right">
                        <a title="Редактировать" href="{{ route('users.edit', $user->id) }}"><i class="fas fa-edit"></i></a>
                        {{ Form::open(['url' => route('users.destroy', $user), 'method' => 'delete', 'onsubmit' => 'return agreeRemove("'.$user->email.'")', 'class' => 'd-inline']) }}
                            <a class="trash user-remove" title="Удалить пользователя" href="#"><i class="fas fa-trash"></i></a>
                        {{ Form::close() }}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    {{ $data['users']->links() }}

@endsection