routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('register', function () {
	abort(404);
});
Route::post('register', function () {
	abort(404);
});

Route::get('/', function () {
	return redirect()->route('templates.index');
});
Route::get('message.jpg', 'Controller@messageViewed')->name('message.view');

Route::middleware(['auth'])->group(function () {
	Route::resource('templates', 'TemplateController');
	Route::resource('users', 'UserController');
	Route::resource('import', 'ImportController')->only(['index', 'store']);
	Route::get('messages', 'MessageController@index')->name('messages.index');	
	Route::post('mailing', 'Controller@mailingRun')->name('mailing.run');
});

resources/views/templates/create.blade.php
@extends('layouts.mailing')

@section('title')
    Создание нового шаблона для письма
@endsection

@section('content')
    {{ Form::open(['url' => route('templates.store'), 'enctype' => 'multipart/form-data']) }}
    <div>
        <div class="form-group">
            {{ Form::label('name', 'Название шаблона', ['class' => 'label-control']) }}
            {{ Form::text('name', null, ['class' => 'form-control', 'id' => 'name', 'placeholder' => 'Введите название']) }}
        </div>
        <div class="form-group">
            {{ Form::label('subject', 'Тема письма', ['class' => 'label-control']) }}
            {{ Form::text('subject', null, ['class' => 'form-control', 'id' => 'subject', 'placeholder' => 'Введите тему письма']) }}
        </div>
        <div class="form-group">
            {{ Form::label('template', 'Шаблон письма', ['class' => 'label-control']) }}
            <p>Список директив:
                @foreach($data['listDirectives'] as $directive)
                    <small><?='{{'.$directive.'}}'?></small>
                @endforeach
            </p>
            {{ Form::textarea('template', null, ['class' => 'form-control'])}}
        </div>
        <div class="files">
            <div class="form-group">
                    {{ Form::file('file[]') }}
                    <a class="clear-input-file trash" href="#"><i class="fa fa-trash"></i></a>
            </div>            
        </div>
        <div class="row">
            <div class="form-group">
                <a title="Еще файл" class="add-more-files" href="#"><i class="fa fa-plus"></i></a>
            </div>
        </div>
    </div>
    <div class="form-group text-center">
            {{ Form::submit('Создать', ['class' => 'btn btn-primary']) }}
            {{ Html::tag('a', 'Назад', ['href' => route('templates.index'), 'class' => 'btn btn-outline-secondary']) }}        
    </div>
    {{ Form::close() }}
    <div class="buffer file">
        <div class="form-group">
            {{ Form::file('file[]') }}
            <a class="remove-input-file trash" href="#"><i class="fa fa-trash"></i></a>
        </div>
    </div>
@endsection

resources/views/templates/edit.blade.php
@extends('layouts.mailing')

@section('title')
    Обновление шаблона
@endsection

@section('content')
    {{ Form::model($data['template'], ['url' => route('templates.update', $data['template']), 'method' => 'patch', 'enctype' => 'multipart/form-data']) }}
    <div>
        <div class="form-group">
            {{ Form::label('name', 'Название шаблона', ['class' => 'label-control']) }}
            {{ Form::text('name', null, ['class' => 'form-control', 'id' => 'name', 'placeholder' => 'Введите название']) }}
        </div>
        <div class="form-group">
            {{ Form::label('subject', 'Тема письма', ['class' => 'label-control']) }}
            {{ Form::text('subject', null, ['class' => 'form-control', 'id' => 'subject', 'placeholder' => 'Введите тему письма']) }}
        </div>
        <div class="form-group">
            {{ Form::label('template', 'Шаблон письма', ['class' => 'label-control']) }}
            <p>Список директив:
                @foreach($data['listDirectives'] as $directive)
                    <small><?='{{'.$directive.'}}'?></small>
                @endforeach
            </p>
            {{ Form::textarea('template', null, ['class' => 'form-control'])}}
        </div>

        @foreach ($data['template']->getMedia() ?? [] as $file)
            <div class="col-12 attach-file mb-2" data-remove-url="{{ route('templates.destroy', $data['template']) }}" data-file-id="{{ $file->id }}">
                <a class="remove-attach-file trash mr-2" href="#"><i class="fa fa-trash"></i></a>
                {{ Html::tag('a', $file->name, ['href' => $file->getUrl()]) }}
            </div>
        @endforeach

        <div class="files">
            <div class="form-group">
                    {{ Form::file('file[]') }}
                    <a class="clear-input-file trash" href="#"><i class="fa fa-trash"></i></a>
            </div>            
        </div>
        <div class="row">
            <div class="form-group">
                <a title="Еще файл" class="add-more-files" href="#"><i class="fa fa-plus"></i></a>
            </div>
        </div>
    </div>
    <div class="form-group text-center">
            {{ Form::submit('Сохранить', ['class' => 'btn btn-primary']) }}
            {{ Html::tag('a', 'Назад', ['href' => route('templates.index'), 'class' => 'btn btn-outline-secondary']) }}        
    </div>
    {{ Form::close() }}
    <div class="buffer file">
        <div class="form-group">
                {{ Form::file('file[]') }}
                <a class="remove-input-file trash" href="#"><i class="fa fa-trash"></i></a>
        </div>
    </div>
@endsection

resources/views/templates/index.blade.php
@extends('layouts.mailing')

@section('title')
    Список всех шаблонных писем
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <a class="btn btn-primary" href="{{ route('templates.create') }}">Создать <i class="fa fa-plus"></i></a>
            </div>                    
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-md-2 mt-3 mb-3">
            <select class="number-view custom-select">
                @foreach ($data['qty'] as $one)
                    <option {{ $data['currentQty'] == $one ? 'selected' : '' }} value="{{ $one }}">{{ $one }}</option>
                @endforeach
            </select>
        </div>
    </div>
    {{ $data['templates']->links() }}
    <table class="table table-striped">
        <thead>
            <th class="w-25">#</th>
            <th class="w-50">Название</th>
            <th class="w-25">&nbsp;</th>
        </thead>
        <tbody>
            @foreach ($data['templates'] ?? [] as $template)
                <tr>
                    <td>{{ $template->id }}</td>
                    <td>{{ $template->name }}</td>
                    <td class="text-right">
                        <a title="Редактировать" href="{{ route('templates.edit', $template->id) }}"><i class="fas fa-edit"></i></a>
                        {{ Form::open(['url' => route('templates.destroy', $template), 'method' => 'delete', 'onsubmit' => 'return agreeRemove("'.$template->name.'")', 'class' => 'd-inline']) }}
                            <a class="trash template-remove" title="Удалить шаблон" href="#"><i class="fas fa-trash"></i></a>
                            <input type="hidden" name="action" value="remove-template">
                        {{ Form::close() }}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
    {{ $data['templates']->links() }}
    
@endsection